workspace: PerformanceApp.xcworkspace
xcodeproj: PerformanceApp.xcodeproj
scheme: PerformanceApp
configuration: Debug
ignore:
  - PerformanceApp/*
  - PerformanceSuite/Tests/*
output_directory: coverage