name: PerformanceSuite Tests

on: push
jobs:
  build:
    name: Build and Test PerformanceApp
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: SwiftLint
        run:
          Pods/SwiftLint/swiftlint
      - name: Build & Test
        env:
          scheme: PerformanceSuite-Unit-Tests
          platform: ${{ 'iOS Simulator' }}
          workspace: PerformanceApp.xcworkspace
        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          xcodebuild test -scheme "$scheme" -workspace "$workspace" -destination "platform=$platform,name=$device" -test-iterations 30 -run-tests-until-failure
